name: Test

on:
  push:
    branches:
      - '*'

jobs:
  test:
    name: Run RSpec
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: wordle_bundle_test
          POSTGRES_USER: wb_user
          POSTGRES_PASSWORD: rootpass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Migrate database
        run: |
          bundle exec rails db:migrate
      - name: Run test
        run: |
          bundle exec rspec
